"""
Django settings for tradeshow project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3(!yoj3&c#@e%h7gc#q+a(*nj+k^+9fx*n-a9ng8e*#tmih98c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'www.exhibiz.in','13.58.171.145']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'tsadmin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'tradeshow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/opt/projects/lead_management/tradeshow/tradeshow/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tradeshow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tradeshow_unicode',
        'USER': 'dbadmin',
        'PASSWORD': '!dbadmin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/opt/projects/lead_management/logs/api.log',
            'formatter':'simple'
        },
        'tsadmin_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/opt/projects/lead_management/logs/tsadmin.log',
            'formatter':'simple'
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['tsadmin_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'api': {
            'handlers': ['api_file'],
            'level': 'DEBUG',
            'propagate': True,
        },        
        'tsadmin': {
            'handlers': ['tsadmin_file'],
            'level': 'DEBUG',
            'propagate': True,
        },        
    },
    'formatters': {
		'simple': {
		            'format': '[%(asctime)s] %(levelname)s %(message)s',
			    'datefmt': '%Y-%m-%d %H:%M:%S'
		        },
    },    
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    '/opt/projects/lead_management/reports/',
]

SERVER = "http://exhibiz.in"
TRADESHOW_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"
TRADESHOW_IMPORT_LOCATION = "/opt/projects/lead_management/import_files"
TRADESHOW_IMPORT_FILE_TYPES = ['.xlsx']
TRADESHOW_REPORT_JS = "/opt/projects/lead_management/tradeshow/tradeshow/scripts/reports.js"
TRADESHOW_REPORT_LOCATION = "/opt/projects/lead_management/reports"
SPECIAL_LOGIN_CODE = "$$$"
ES_HOST = "exhibiz.in:9200"
TSADMIN_LOGIN_REDIRECT_URL = "%s/tsadmin/dashboard/" % SERVER
TSADMIN_LOGIN_URL = "%s/tsadmin/login/" % SERVER
